import AuthenticationProtected from "@/components/AuthenticationProtected";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const source_code_pro = Source_Code_Pro({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${source_code_pro.className}`}>
      <body>
        <AuthProvider>
          <AuthenticationProtected>
            {children}
            <Toaster />
          </AuthenticationProtected>
        </AuthProvider>
      </body>
    </html>
  );
}
